# Generated by Django 4.1.2 on 2023-01-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0003_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
