# Generated by Django 4.1.2 on 2023-01-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0009_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('Pakistan', 'Pakistan'), ('India', 'India'), ('Bangladesh', 'Bangladesh')], max_length=50, null=True),
        ),
    ]
