# Generated by Django 4.1.2 on 2023-01-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0012_order_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Cash_on_delivery', 'Cash_on_delivery'), ('Stripe', 'Stripe')], max_length=40, null=True),
        ),
    ]
