# Generated by Django 4.1.2 on 2023-01-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
