# Generated by Django 4.1.2 on 2023-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0008_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'paypal'), ('cash_on_delivery', 'cash_on_delivery'), ('stripe', 'stripe')], max_length=40, null=True),
        ),
    ]
