# Generated by Django 4.1.2 on 2023-01-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0011_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
